### ISSUE TITLE
Add houdini example scene

### ISSUE THREAD

**Issue by goofoo** [rgoldade/GeometricMultigridPressureSolver#1]
Hi Goldade.
Please add houdini example scene and more description about project.
Thanks.

**Comment by rgoldade** [comment]
Sure! Will do.

**Comment by rgoldade** [comment]
Now that the SIGGRAPH paper deadline has passed I actually have time to answer this issue. Thank you for your patience.

**Comment by goofoo** [comment]
Cool.
Maybe you can share info about your new siggraph paper? If for this time you cant public, send on mail. Thanks.

**Comment by rgoldade** [comment]
I added a diagnostic and a test scene file to use with Houdini 18.0. I also added a brief write up of how to build it in the readme.

As for the paper, the submission is anonymous so I can't share anything at this time. Hopefully it gets accepted and then I will be happy to share it. Thanks for understanding.
