### ISSUE TITLE
Windows install instructions ?

### ISSUE THREAD

**Issue by NicTanghe** [rgoldade/GeometricMultigridPressureSolver#2]
Hello my school is forcing us to use windows unfortunately.

Is it possible 4 you to figure out the installation instructions with me ?
The 2-minute papers video on your work will probably generate some traffic With more Windows users in it.

i have no idea where to look on the hdk i assume i have to go here https://www.sidefx.com/docs/hdk/_h_d_k__i_o.html

**Comment by NicTanghe** [comment]
Installation instructions found after 2 seconds of work

Compiling on Windows (MSVC) with hcustom

To compile HDK code on Windows using MSVC, open the Windows START menu and choose Side Effects Software -> Houdini X.Y.ZZZ -> Command-line Tools from your program list. This will launch a command shell with the Houdini environment initialized. hcustom will autodetect your Microsoft Visual C++ distribution. You can confirm that it's correct by running hcustom --output_msvcdir . To manually override this, set the MSVCDir environment variable to point to the Microsoft Visual C++ distribution. Note that this directory should have the subdirectories bin, include, and lib.

Here is an example:
cd /D %HFS%\toolkit
xcopy /S samples C:\samples
cd /D C:\samples\SOP\SOP_Star
hython %HH%/python2.7libs/generate_proto.py SOP_Star.C SOP_Star.proto.h
hcustom SOP_Star.C

Other than using hcustom, one can build using GNU Make or Visual Studio's nmake, see the Compiling with Makefiles section.

If you wish to build from the Visual Studio IDE, then it's suggested that you use CMake instead, see the Compiling with CMake section.

For other build systems, you need to use the same compiler settings as hcustom. To see what they are, you can run "hcustom --cflags" for the compiler options, and "hcustom --ldflags" for the linker options.

**Comment by rgoldade** [comment]
Thanks! I'll add a link to the HDK documentation so people don't have to go
searching for it.
